export const WORD_PAIRS: Array<[string, string]> = [
  ["Chat", "Tigre"], ["Chien", "Loup"], ["Lion", "Panthère"], ["Cheval", "Zèbre"],
  ["Dauphin", "Requin"], ["Aigle", "Faucon"], ["Lapin", "Lièvre"], ["Souris", "Hamster"],
  ["Vache", "Mouton"], ["Poule", "Canard"], ["Plage", "Piscine"], ["Mer", "Lac"],
  ["Montagne", "Colline"], ["Forêt", "Jungle"], ["Désert", "Savane"], ["Île", "Presqu'île"],
  ["Paris", "Londres"], ["New York", "Los Angeles"], ["Italie", "Espagne"], ["Japon", "Corée"],
  ["Coca-Cola", "Pepsi"], ["Sprite", "7Up"], ["Nutella", "Confiture"], ["Burger", "Kebab"],
  ["Pizza", "Tarte"], ["Pâtes", "Riz"], ["Frites", "Chips"], ["Glace", "Sorbet"],
  ["Croissant", "Pain au chocolat"], ["Pomme", "Poire"], ["Fraise", "Framboise"], ["Citron", "Orange"],
  ["Pastèque", "Melon"], ["Carotte", "Concombre"], ["Ketchup", "Mayonnaise"], ["Fourchette", "Cuillère"],
  ["Couteau", "Ciseaux"], ["Assiette", "Bol"], ["Verre", "Tasse"], ["Frigo", "Congélateur"],
  ["Four", "Micro-ondes"], ["Canapé", "Fauteuil"], ["Lit", "Canapé"], ["Douche", "Baignoire"],
  ["Fenêtre", "Porte"], ["Lampe", "Bougie"], ["Télévision", "Écran"], ["Télécommande", "Manette"],
  ["Téléphone", "Tablette"], ["Ordinateur", "Console"], ["Clavier", "Piano"], ["Souris", "Trackpad"],
  ["AirPods", "Casque"], ["YouTube", "TikTok"], ["Instagram", "Snapchat"], ["Discord", "WhatsApp"],
  ["Google", "Bing"], ["Netflix", "Disney+"], ["Spotify", "Deezer"], ["Roblox", "Minecraft"],
  ["Fortnite", "Apex Legends"], ["PlayStation", "Xbox"], ["Mario", "Sonic"], ["Pokémon", "Digimon"],
  ["Football", "Basket"], ["Tennis", "Badminton"], ["Boxe", "Karaté"], ["Natation", "Plongée"],
  ["Ski", "Snowboard"], ["Vélo", "Trottinette"], ["Voiture", "Moto"], ["Bus", "Tramway"],
  ["Métro", "Train"], ["Avion", "Hélicoptère"], ["Bateau", "Sous-marin"], ["Taxi", "Uber"],
  ["École", "Collège"], ["Professeur", "Surveillant"], ["Cahier", "Classeur"], ["Stylo", "Crayon"],
  ["Gomme", "Correcteur"], ["Règle", "Équerre"], ["Maths", "Physique"], ["Histoire", "Géographie"],
  ["Récréation", "Pause"], ["Cantine", "Restaurant"], ["Cinéma", "Théâtre"], ["Film", "Série"],
  ["Acteur", "Chanteur"], ["Rap", "Pop"], ["Guitare", "Basse"], ["Concert", "Festival"],
  ["Photo", "Vidéo"], ["Livre", "BD"], ["Journal", "Magazine"], ["Super-héros", "Vilain"],
  ["Spider-Man", "Batman"], ["Iron Man", "Superman"], ["Harry Potter", "Mercredi"], ["Zombie", "Vampire"],
  ["Fantôme", "Esprit"], ["Police", "Gendarmerie"], ["Pompier", "Ambulancier"], ["Médecin", "Infirmier"],
  ["Hôpital", "Pharmacie"], ["Banque", "Assurance"], ["Magasin", "Supermarché"], ["Restaurant", "Fast-food"],
  ["Anniversaire", "Noël"], ["Halloween", "Carnaval"], ["Cadeau", "Surprise"], ["Vacances", "Week-end"],
  ["Soleil", "Lune"], ["Étoile", "Planète"], ["Pluie", "Neige"], ["Orage", "Tempête"],
  ["Chaud", "Froid"], ["Matin", "Soir"], ["Rire", "Sourire"], ["Peur", "Stress"],
  ["Rapide", "Pressé"], ["Géant", "Grand"], ["Secret", "Mystère"], ["Chance", "Hasard"]
];
